- default_parameters:
    max_frequency: 150
    # maximum database size in MB
    max_database_size: 102400
    # whether or not to create a new DB after max size is reached
    split_database: false
    db_name: 'logs'
- zyre:
    name: black_box_001
    groups:
        - ROPOD
    message_types:
        - CMD
        - plan
        - progress
        - RobotPose2D
- ros:
    ros_master_uri: localhost
    topics:
        - topic:
            name: /dynamic_obstacle_map_ref
            type: nav_msgs/OccupancyGrid
            variable_names: []
            max_frequency: 5
            metadata:
                ros:
                    topic_name: /dynamic_obstacle_map_ref
                    msg_type: nav_msgs/OccupancyGrid
                    direct_msg_mapping: true
        - topic:
            name: /static_obstacle_map_ref
            type: nav_msgs/OccupancyGrid
            variable_names: []
            max_frequency: 1
            metadata:
                ros:
                    topic_name: /static_obstacle_map_ref
                    msg_type: nav_msgs/OccupancyGrid
                    direct_msg_mapping: true

        - topic:
            name: /hsrb/odom
            type: nav_msgs/Odometry
            variable_names: [position/x, position/y, position/z, orientation/x, orientation/y, orientation/z, orientation/w, linear/x, linear/y, linear/z, angular/x, angular/y, angular/z]
            max_frequency: 30
            metadata:
                ros:
                    topic_name: /hsrb/odom
                    msg_type: nav_msgs/Odometry
                    direct_msg_mapping: true
        - topic:
            name: /hsrb/base_scan
            type: sensor_msgs/LaserScan
            variable_names: [frame_id, angle_min, angle_max, angle_increment, time_increment, scan_time, range_min, range_max, ranges]
            max_frequency: 30
            metadata:
                ros:
                    topic_name: /hsrb/base_scan
                    msg_type: sensor_msgs/LaserScan
                    direct_msg_mapping: true
        - topic:
            name: /laser_2d_pose
            type: geometry_msgs/PoseWithCovarianceStamped
            variable_names: [frame_id, angle_min, angle_max, angle_increment, time_increment, scan_time, range_min, range_max, ranges]
            max_frequency: 10
            metadata:
                ros:
                    topic_name: /laser_2d_pose
                    msg_type: geometry_msgs/PoseWithCovarianceStamped
                    direct_msg_mapping: true

        - topic:
            name: /hsrb/command_velocity
            type: geometry_msgs/Twist
            variable_names: [linear/x, linear/y, linear/z, angular/x, angular/y, angular/z]
            max_frequency: 30
            metadata:
                ros:
                    topic_name: /hsrb/command_velocity
                    msg_type: geometry_msgs/Twist
                    direct_msg_mapping: true
        - topic:
            name: /tf
            type: tf2_msgs/TFMessage
            variable_names: []
            max_frequency: 150
            metadata:
                ros:
                    topic_name: /tf
                    msg_type: tf2_msgs/TFMessage
                    direct_msg_mapping: true
        - topic:
            name: /mas_perception/detection_result
            type: sensor_msgs/Image
            variable_names: []
            max_frequency: 1
            metadata:
                ros:
                    topic_name: /mas_perception/detection_result
                    msg_type: sensor_msgs/Image
                    direct_msg_mapping: true
        - topic:
            name: /dmp_executor/path
            type: nav_msgs/Path
            variable_names: []
            max_frequency: 1
            metadata:
                ros:
                    topic_name: /dmp_executor/path
                    msg_type: nav_msgs/Path
                    direct_msg_mapping: true
        - topic:
            name: /arm_1/arm_controller/cartesian_velocity_command
            type: geometry_msgs/TwistStamped
            variable_names: []
            max_frequency: 30
            metadata:
                ros:
                    topic_name: /arm_1/arm_controller/cartesian_velocity_command
                    msg_type: geometry_msgs/TwistStamped
                    direct_msg_mapping: true
        - topic:
            name: /event
            type: mdr_monitoring_msgs/Event
            variable_names: []
            max_frequency: 10
            metadata:
                ros:
                    topic_name: /event
                    msg_type: mdr_monitoring_msgs/Event
                    direct_msg_mapping: true
        - topic:
            name: /hsrb/wrist_wrench/compensated
            type: geometry_msgs/WrenchStamped
            variable_names: []
            max_frequency: 30
            metadata:
                ros:
                    topic_name: /hsrb/wrist_wrench/compensated
                    msg_type: geometry_msgs/WrenchStamped
                    direct_msg_mapping: true
        - topic:
            name: /mdr_actions/perceive_plane_server/result
            type: mdr_perceive_plane_action/PerceivePlaneActionResult
            variable_names: []
            max_frequency: 10
            metadata:
                ros:
                    topic_name: /mdr_actions/perceive_plane_server/result
                    msg_type: mdr_perceive_plane_action/PerceivePlaneActionResult
                    direct_msg_mapping: true

